### ISSUE TITLE
Pferderassen in Minispielen gewinnen

### ISSUE THREAD

**Issue by OliverNiebsch** [PhilippGrulich/HAW-SE2-projecthorse#113]
Hannoveraner in Parcours
Friese in Puzzle und Applerun
Shetty in Memory und Hütchenspiel

Das Erhalten der Pferderassen sollen z.B. bei einer bestimmten Punktzahl zu 20% erfolgen.

**Comment by FrancisAO** [comment]
Der Hannoveraner kann jetzt in Parcours mit mit einer Wahrscheinlichkeit von 20% gewonnen werden.

**Comment by Scrittl** [comment]
Friese nun erhältlich in Applerun (20% Chance)

**Comment by ngochuyen92** [comment]
Shetty kann jetzt in MemorySpiel mit mit einer Wahrscheinlichkeit von 20% gewonnen werden.

**Comment by fabianHAW** [comment]
upps..vergessen zu kommentieren, dass im hütchenspiel der shetti auch gewonnen wird...
