### ISSUE TITLE
Metriken

### ISSUE THREAD

**Issue by OliverNiebsch** [PhilippGrulich/HAW-SE2-projecthorse#118]
Es sollen sinnvolle Metriken für unser Projekt erhoben werden.

**Comment by fabianHAW** [comment]
alle metriken sind nun erhoben und dokumentiert. ebenso die javadoc erstellt. schaut doch bitte unter dem ordner Dokumentation nach (die javadoc habe ich dort auch hineingeschoben). dort ist alles aufgeführt. was nun noch fehlt sind ein paar testdokumentationen...
