### ISSUE TITLE
Präsentation vorbereiten

### ISSUE THREAD

**Issue by vikwin** [PhilippGrulich/HAW-SE2-projecthorse#133]

**Comment by Scrittl** [comment]
Screenshots sind in der Dropbox

**Comment by FrancisAO** [comment]
Parcours:
Spielprinzip
Beute

**Comment by vikwin** [comment]
Punkte für WorldMap:
Anschauliche Navigation
Erweiterbarkeit

**Comment by PhilippGrulich** [comment]
City:
Information zur Stadt
Erweiterbarkeit

**Comment by MariaAI** [comment]
Puzzle:
Bilderauswahl
eigentliches Puzzlespiel

**Comment by ngochuyen92** [comment]
Memory Spiel:
Spielprinzip
mögliche Gewinne
