### ISSUE TITLE
scaleby skaliert nicht zu klein...

### ISSUE THREAD

**Issue by fabianHAW** [PhilippGrulich/HAW-SE2-projecthorse#141]
wenn ich auf dem player scaleby() aufrufe, statt setscale(), dann wird das pferd nicht klein genug skaliert, sodass es unter den hut passt..was nun? oder muss die scaleby() noch überschrieben werden? vorher mit setsclae() war alles wunderbar ;)

**Comment by vikwin** [comment]
Ist dieses Thema jetzt abgehakt?
