### ISSUE TITLE
coderichtlinien einhalten

### ISSUE THREAD

**Issue by fabianHAW** [PhilippGrulich/HAW-SE2-projecthorse#157]
bitte schaut nach, dass überall die coderichtlinien eingehalten werden.

**Comment by FrancisAO** [comment]
In Parcours werden jetzt die Coderichtlinien eingehalten.

**Comment by fabianHAW** [comment]
hier fehlt auch noch das memoryspiel komplett und im package platform sind noch ein paar sachen nicht ganz den richtlinien entsprechend. bei den anderen warnings handelt es sich nur um so kleinkram..das wollten wir ja nicht ganz so haargenau nehmen?! sonst pass ich das noch eben an...

**Comment by ngochuyen92** [comment]
Die Code für MemorySpiel sind schon komplett. Die Coderichtlinien und
Kommentare dafür mache ich heute Abend fertig.

2015-01-09 9:53 GMT+01:00 fabianHAW <notifications@github.com>:

**Comment by ngochuyen92** [comment]
Fertig!

**Comment by fabianHAW** [comment]
in der endlessbackground klasse fehlte noch ein javadoc und ein zwei dinge waren nicht ganz den richtlinien entsprechend. ebenso habe ich in der checkstyle-config die prüfung heraus genommen, dass hinter klammen kein leerzeichen stehen darf ;) 
es gibt nun nur noch 2 klassen die nicht zu 100% die richtlinien einhalten. aber das ist nur kleinkram und können wir ignorieren ;)
