### ISSUE TITLE
Memory Spiel Test und Doku anlegen

### ISSUE THREAD

**Issue by ngochuyen92** [PhilippGrulich/HAW-SE2-projecthorse#165]

**Comment by vikwin** [comment]
Reopen, weil du nichts hochgeladen hast.

**Comment by ngochuyen92** [comment]
Bist du sicher? Ich hab die Code hochgeladen, bevor ich den Issue geschlossen habe.

**Comment by ngochuyen92** [comment]
Die hab ich rechtszeitig hochgeladen, das Commit war bei mir schon weg. Bitte noch mal prüfen

**Comment by vikwin** [comment]
Welchen code? Es geht hier um ein Textdokument im odt format, welches test
User stories definiert und worin diese dann protokolliert durchgeführt
werden, so wie es alle anderen im ordner Dokumentation/Testen auch gemacht
haben. Da liegt aber keine Datei von dir...
Am 12.01.2015 16:53 schrieb "ngochuyen92" <notifications@github.com>:

**Comment by vikwin** [comment]
Datei ist jetzt da
