### ISSUE TITLE
Fehlende Linzenzangaben / Überflüssige Lizenzangaben

### ISSUE THREAD

**Issue by vikwin** [PhilippGrulich/HAW-SE2-projecthorse#173]
Bitte alle die eigenen Assets prüfen und hier bestätigen

**Comment by MariaAI** [comment]
fertig

**Comment by Scrittl** [comment]
erledigt

**Comment by vikwin** [comment]
fertig

**Comment by FrancisAO** [comment]
fertig

**Comment by vikwin** [comment]
Fehlen also noch Philipp und Huyen. Wie sieht es bei euch aus?

**Comment by ngochuyen92** [comment]
fertig!

**Comment by PhilippGrulich** [comment]
ist jetzt auch fertig

**Comment by fabianHAW** [comment]
beim memoryspiel und ein bild für die ui wurden nicht gefunden. das lag aber nur an den einträgen in der lizenzdatei..es werden alle lizenzen erkannt und sind korrekt. ob nun tatsächlich alle assets in den lizenzdateien eingetragen sind habe ich nun nicht überprüft! sollte aber alles tutti sein :)
