### ISSUE TITLE
Parcour - keine Sprunganimation

### ISSUE THREAD

**Issue by Scrittl** [PhilippGrulich/HAW-SE2-projecthorse#175]
bei mir wird beim Springen nicht die Sprunganimation angezeigt. Das Pferd fliegt einfach in Lauf-Animation nach oben.

**Comment by FrancisAO** [comment]
Die Sprunganimation habe ich jetzt drinnen. Die Animation wird während des Sprungs allerdings nicht ganz angzeigt, egal wie lange die Animation läuft bzw. wie lange der Sprung dauert. Man erkennt aber, dass das Pferd springt u. nicht mehr in Laufanimation nach oben springt.

**Comment by fabianHAW** [comment]
ich glaube die sprunganimation geht auch nicht weiter als sie so nun implementiert ist! sieht aber doch gut aus finde ich :)

**Comment by FrancisAO** [comment]
Danke, die geht schon noch weiter, aber nur dann, wenn das Pferd nicht springt.

**Comment by Scrittl** [comment]
Wow, das war nicht einfach zu finden... Aber ich glaub ich hab es.

In deiner GameObjectLogic.handleJump() setzt du erst "gameField.getPlayer().setPosition(x, y);" anschließend kommt die Abfrage ob der player bereits auf dem Boden ist. und wenn ja wird die Animation gestoppt.

Der dritte Positionsvektor deiner Sprung animation ist auf dem Boden. Wenn du also den Scheitelpunkt oben überschritten hast, ist das nächste Ziel der Boden. Da du aber sofort die Position setzt, denkt die If-Abfrage das dein Player schon auf dem Boden ist und ruft deswegen setPlayerJump(false); auf. Deswegen stoppt die Animation wenn du oben bist.

Wenn du die setPosition Methode auskommentierst, siehst du das der Sprung komplett animiert ist. (Allerdings stimmen dann die Positionen nichtmehr.)

Als Dirty-QuickFix könntest du noch einen extra Vektor als vorletztes Ziel - ein Pixel über dem Boden einfügen. 
(Deine Berechnung kann ich aber leider nicht Nachvollziehen um das eben umzusetzen.)

**Comment by FrancisAO** [comment]
Ok, danke das du da nochmal drüber geschaut hast. Es werden allerdings 22 Vektoren berechnet, zumindest in der Dekstopvariante. Für die Android hatte ich jetzt keine Zeit mehr, aber daran, dass das Pferd nach Überschreitung des Scheitelpunktes sofort auf die y-Ausgangsposition geht, lag es nicht. Der Fehler war in der AnimationAction bzw. in der Geschwindigkeit, mit der ich den AnimationSpeed vom Player setze. Die AnmiationAction zeigt den nächsten spriteIndex erst an, wenn deltaSum >= frameduration ist. Frameduration wird in der AnimationActiondurch  MIN_FRAMEDURATION / speed berechnet und speed ist der AnimationSpeed. Je größer also AnimationSpeed, desto eher wird die Animation angezeigt, was ziemlich logisch klingt.
