### ISSUE TITLE
AppleRun Tempo der Pferde wird von Neigungssensor übergangen

### ISSUE THREAD

**Issue by vikwin** [PhilippGrulich/HAW-SE2-projecthorse#176]
Wenn man das Pferd per Swipe oder Klick bewegt, sieht man dass die Pferde unterschiedlich schnell sind. Nutzt man aber den Neigungssensor, sind die Pferde viel schneller.

**Comment by Scrittl** [comment]
Alle Bewegungen sind gleich schnell; alle werden durch den gleichen Methodenaufruf initiiert...

Ich lass den Issue erstmal noch offen - reden wir morgen nochmal kurz drüber.
