### ISSUE TITLE
texturenotfound exception in der lootgalery

### ISSUE THREAD

**Issue by fabianHAW** [PhilippGrulich/HAW-SE2-projecthorse#178]
wenn man in der loot galery ist und dann von hütchenspiel oder dem applerun, je nachdem was man schon so gewonnen hat, in die, ich nehme an, lootanzeige des parcours spiels geht, dann wird die exception geschmissen, dass der hannoveraner in den assets nicht gefunden wird. hat das ggf. was mit den änderungen im parcours zu tun? da es vorher noch funktioniert hatte sich die loots des parcours spiels anzusehen. in dem save-file steht als loot noch drin, dass der hannoveraner ein parcoursloot sei.

**Comment by FrancisAO** [comment]
Das liegt wahrscheinlich an den Änderungen die ich in Parcours gemacht habe. Der Hannoveraner sollte nicht mehr in der Lootgallery angezeigt werden, da er auch nicht mehr im Savegame gespeichert wird. Ich würde das Savegame löschen, dann sollte der Fehler nicht mehr auftreten.

**Comment by fabianHAW** [comment]
ah ok..habe den eintrag einmal gelöscht und dann nochmal gespielt und den hannoveraner gewonnen. ein eintrag im savegame wurde nicht mehr vorgenommen. wenn also wer die savegame-kopie verwendet, dann den eintrag einfach raus löschen..
