### ISSUE TITLE
Parcours: 20% Hannoveraner Chance

### ISSUE THREAD

**Issue by FrancisAO** [PhilippGrulich/HAW-SE2-projecthorse#179]
Habe vorhin beim Testen vergessen die 20% Wahrscheinlichkeit des Gewinns vom Hannoveraner einzukommentieren - werde das heute aber noch machen, bis 15:00 Uhr wird das aber nichts.

**Comment by Scrittl** [comment]
Copy & Paste Vorlage:
		double roll = Math.random();
		if (roll <= 0.2f
				&& !SaveGameManager.getLoadedGame().getSpecifiedLoot(RaceLoot.class).contains(HorseRace.HANNOVERANER)) {
			this.chest.addLootAndShowAchievment(new RaceLoot(HorseRace.HANNOVERANER));
		}

**Comment by FrancisAO** [comment]
Danke, aber die 20% sind schon implementiert. Hatte vorhin nur zum testen die Wahrscheinlichkeit auf 100% gesetzt.
