### ISSUE TITLE
UTF-8 Encoding wird nicht von allen eingehalten

### ISSUE THREAD

**Issue by vikwin** [PhilippGrulich/HAW-SE2-projecthorse#90]
So wie es aussieht scheint nicht jeder sein Git so eingestellt zu haben, dass der Code jeweils mit UTF-8 Encoding auf Github landet bzw. vielleicht auch von dort gezogen wird.
Das führt zu Fehlern bei Verwendung von Sonderzeichen wie Umlauten im Quellcode, z. B. bei Strings die im Spiel angezeigt werden sollen.
Wer eine allgemeingültige Lösung hierfür kennt oder findet bitte hier posten.

**Comment by fabianHAW** [comment]
ich habe mal probeweise eine javadoc erstellt und festgestellt, dass im browser die umlaute wieder ganz merkwürdig dargestellt werden: https://pub.informatik.haw-hamburg.de/home/pub/r/reiber_fabian/javadoc/index.html in der klasse AnimationAction ist ein beispiel zu sehen. woran kann das wieder liegen? habe in eclipse alles auf utf-8 stehen und in der browser-config ist auch alles ok meines erachtens. im netz habe ich nix hilfreiches gefunden.

**Comment by FrancisAO** [comment]
Das liegt wahrscheinlich nicht daran, dass der UTF-8 Standard nicht von allen eingehalten wird. Ich habe in meinem Workspace auch utf8 eingestellt, in der Javadoc werden mir meine eigenen Javadoc-Kommentare aber falsch angezeigt obwohl sie im Code selbst richtig dargestellt werden.
Also hat das nichts - oder nicht nur - mit den Einstellungen im Workspace zu tun.
Ich habe mal probeweise eine Klasse von mir in utf8 mit und ohne BOM konvertiert, aber das explizite konvertieren ändert auch nichts an dem Sachverhalt (mit BOM schmeißt Eclipse ohnehin Errors).

**Comment by vikwin** [comment]
Der Fehler im Javadoc liegt daran, dass du beim Konvertieren nicht explizit angegeben hast, dass auch das Javadoc in UTF-8 verfasst sein soll. Daher fehlt in den HTML Metadaten das encoding=utf-8 Flag. Ohne dieses versucht der Browser die Umlaute nach standard ISO / ASCII / Schießmichtot zu dekodieren und erzeugt diese tollen Zeichen.

Um das Javadoc korrekt zu erstellen musst du beim Export unter Eclipse auf dem letzen Bildschirm unter Extra Javadoc options folgende Zeile einfügen:

-encoding UTF-8 -charset UTF-8 -docencoding UTF-8


Da der Fall hiermit gelöst ist, closed.

**Comment by fabianHAW** [comment]
oh ok..hatte bei den einstellungen geschaut, aber nichts wirklich brauchbares entdeckt. danke für den tipp!
